# Generated by Django 3.0.1 on 2022-06-04 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_programming_languages'),
        ('account', '0003_googlelogin'),
    ]

    operations = [
    ]
