# Generated by Django 3.0.1 on 2022-06-11 19:50

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_programming_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='programming_languages',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Java', 'Java'), ('Python 3', 'Python 3'), ('C++', 'C++')], default=None, max_length=17),
        ),
    ]
