# Generated by Django 3.0.1 on 2022-06-12 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20220612_0020'),
        ('account', '0004_merge_20220605_0257'),
    ]

    operations = [
    ]
