# Generated by Django 3.0.1 on 2022-06-13 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_merge_20220612_2155'),
        ('account', '0005_merge_20220612_2228'),
    ]

    operations = [
    ]
