# Generated by Django 3.0.1 on 2022-06-17 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_merge_20220613_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='national_code',
        ),
    ]
