# Generated by Django 3.0.1 on 2022-06-18 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_profile_national_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googlelogin',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='googlelogin',
            name='expires_in',
        ),
        migrations.RemoveField(
            model_name='googlelogin',
            name='id_token',
        ),
        migrations.RemoveField(
            model_name='googlelogin',
            name='scope',
        ),
        migrations.AddField(
            model_name='googlelogin',
            name='code',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
