# Generated by Django 3.0.1 on 2022-06-29 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_profile_national_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='programming_languages',
        ),
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programming_language_title', models.CharField(choices=[('Java', 'Java'), ('Python 3', 'Python 3'), ('C++', 'C++')], max_length=100)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programming_languages', to='account.Profile')),
            ],
        ),
    ]
