# Generated by Django 3.0.1 on 2022-06-30 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20220629_1714'),
        ('account', '0008_auto_20220630_0152'),
    ]

    operations = [
    ]
