# Generated by Django 3.0.1 on 2022-06-30 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20220630_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_year',
        ),
    ]
