# Generated by Django 3.0.1 on 2022-07-02 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_profile_birth_year'),
        ('account', '0008_auto_20220618_0636'),
    ]

    operations = [
    ]
