# Generated by Django 3.0.1 on 2022-07-04 20:42

import utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_merge_20220702_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=utils.fields.WEBPField(blank=True, null=True, upload_to='profile_images'),
        ),
    ]
