# Generated by Django 3.0.1 on 2022-07-06 19:40

from django.db import migrations
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20220704_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=utils.fields.WEBPField(blank=True, null=True, upload_to='profile_images'),
        ),
    ]
