# Generated by Django 3.0.1 on 2022-07-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20220704_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobexperience',
            name='description',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
