# Generated by Django 3.0.1 on 2022-07-16 06:27

from django.db import migrations
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20220711_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=utils.fields.WEBPField(blank=True, null=True, upload_to='profile_images'),
        ),
    ]
