# Generated by Django 3.0.1 on 2022-08-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20220716_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
