# Generated by Django 4.0.4 on 2022-04-18 20:16

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_title', models.CharField(max_length=100)),
                ('team_title', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name_fa', models.CharField(max_length=100)),
                ('last_name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name_fa', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(upload_to=website.models.staff_upload_path)),
            ],
        ),
    ]
