# Generated by Django 4.0.4 on 2022-04-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_prize'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastAIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_year', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('title_en', models.CharField(blank=True, max_length=100)),
                ('title_fa', models.CharField(max_length=100)),
                ('description_en', models.TextField(blank=True, max_length=1000)),
                ('description_fa', models.TextField(max_length=1000)),
                ('firstTeam', models.TextField(max_length=100)),
                ('secondTeam', models.TextField(max_length=100)),
                ('thirdTeam', models.TextField(max_length=100)),
            ],
        ),
    ]
