# Generated by Django 3.0.1 on 2022-04-28 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_pastaic'),
        ('website', '0002_auto_20220425_1648'),
    ]

    operations = [
    ]
