# Generated by Django 3.0.1 on 2022-04-28 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20220428_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequentlyAskedQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('question_en', models.CharField(max_length=1000)),
                ('question_fa', models.CharField(max_length=1000)),
                ('answer_en', models.CharField(max_length=1000)),
                ('answer_fa', models.CharField(max_length=1000)),
            ],
        ),
    ]
