# Generated by Django 3.0.1 on 2022-05-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20220516_0106'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('title_en', models.CharField(max_length=100)),
                ('title_fa', models.CharField(max_length=100)),
                ('text_en', models.TextField()),
                ('text_fa', models.TextField()),
                ('day', models.CharField(blank=True, max_length=100, null=True)),
                ('month', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
    ]
