# Generated by Django 3.0.1 on 2022-06-10 22:39

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_timelineevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequentlyaskedquestions',
            name='show_on_landing_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news',
            name='importance',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
