# Generated by Django 3.0.1 on 2022-06-12 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20220612_2101'),
        ('website', '0011_auto_20220612_2202'),
    ]

    operations = [
    ]
