# Generated by Django 3.0.1 on 2022-06-13 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_news_importance_faq_show_landing_page'),
        ('website', '0012_merge_20220612_2227'),
    ]

    operations = [
    ]
