# Generated by Django 3.0.1 on 2022-06-22 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_merge_20220613_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastaic',
            name='description_fa',
        ),
        migrations.RemoveField(
            model_name='pastaic',
            name='firstTeam',
        ),
        migrations.RemoveField(
            model_name='pastaic',
            name='secondTeam',
        ),
        migrations.RemoveField(
            model_name='pastaic',
            name='thirdTeam',
        ),
        migrations.RemoveField(
            model_name='pastaic',
            name='title_fa',
        ),
    ]
