# Generated by Django 3.0.1 on 2022-06-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20220622_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=100)),
                ('title_fa', models.CharField(max_length=100)),
            ],
        ),
    ]
