# Generated by Django 3.0.1 on 2022-06-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_statistic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastaic',
            name='description_en',
        ),
        migrations.AddField(
            model_name='pastaic',
            name='description_fa',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
