# Generated by Django 3.0.1 on 2022-07-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20220622_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='UTMTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('count', models.IntegerField(default=0)),
                ('code', models.CharField(max_length=4)),
            ],
        ),
    ]
