# Generated by Django 3.0.1 on 2022-06-30 06:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20220622_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='UTMTracker',
            fields=[
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('count', models.IntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
