# Generated by Django 3.0.1 on 2022-07-03 19:41

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_utmtracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastaic',
            name='image',
            field=models.ImageField(upload_to=website.models.pastaic_upload_path),
        ),
    ]
