# Generated by Django 3.0.1 on 2022-07-02 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_utmtracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='utmtracker',
            name='code',
            field=models.CharField(max_length=4, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='utmtracker',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
