# Generated by Django 3.0.1 on 2022-07-04 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_auto_20220704_0011'),
        ('website', '0018_auto_20220704_1432'),
    ]

    operations = [
    ]
