# Generated by Django 3.0.1 on 2022-07-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_statistic_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='app_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
