# Generated by Django 3.0.1 on 2022-07-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_statistic_app_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequentlyaskedquestions',
            name='answer_en',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='frequentlyaskedquestions',
            name='answer_fa',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='frequentlyaskedquestions',
            name='question_en',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='frequentlyaskedquestions',
            name='question_fa',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='news',
            name='body',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='preview',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='pastaic',
            name='description_fa',
            field=models.TextField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.TextField(max_length=3000, null=True),
        ),
    ]
