# Generated by Django 3.0.1 on 2022-08-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='callback_url',
            field=models.URLField(default='https://api.aichallenge.ir/api/v1/payment/callback'),
        ),
    ]
