# Generated by Django 3.0.1 on 2022-07-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_finalist',
            field=models.BooleanField(default=False),
        ),
    ]
