# Generated by Django 3.0.1 on 2022-08-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_team_is_finalist'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='bot_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='team',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
    ]
