# Generated by Django 3.0.1 on 2022-07-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_scoreboard_scoreboardrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='infra_token',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='map',
            name='name',
            field=models.CharField(max_length=3000, unique=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='infra_token',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='log_file_token',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='infra_compile_message',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=3000, unique=True),
        ),
    ]
