# Generated by Django 3.0.1 on 2022-08-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0004_auto_20220725_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='clan_images/'),
        ),
        migrations.AlterField(
            model_name='map',
            name='file',
            field=models.FileField(upload_to='map/'),
        ),
        migrations.AlterField(
            model_name='match',
            name='log',
            field=models.FileField(blank=True, null=True, upload_to='match_logs/'),
        ),
    ]
