# Generated by Django 3.0.1 on 2022-08-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0005_auto_20220804_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='config_file',
            field=models.FileField(blank=True, null=True, upload_to='map/'),
        ),
    ]
